INSERT INTO category (description) VALUES ('Biography');
INSERT INTO category (description) VALUES ('Action');
INSERT INTO category (description) VALUES ('Comic');
INSERT INTO category (description) VALUES ('Drama');
INSERT INTO category (description) VALUES ('Fantasy');
INSERT INTO category (description) VALUES ('Horror');
INSERT INTO category (description) VALUES ('Romance');
INSERT INTO location (description) VALUES ('My Room');
INSERT INTO location (description) VALUES ('Living Room');
INSERT INTO location (description) VALUES ('On Loan');
